Use util-linux's getopt for argument parsing.

diff --git a/apt-proxy-import b/apt-proxy-import
--- a/apt-proxy-import
+++ b/apt-proxy-import
@@ -55,12 +55,16 @@ debug()
 unset VERBOSE
 
 # Parse command line
-while [ $# -gt 0 ]; do
+ARGS=`getopt -o c:hvd --long \
+	config-file:,help,version,verbose \
+	-n "$0" -- "$@"`
+if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
+eval set -- "$ARGS"
+while true ; do
 	case "$1" in
-	  '-c')
- 		shift
-		CONFIG_FILE="$1"
-		shift
+	  '-c'|'--config-file')
+		CONFIG_FILE="$2"
+		shift 2
 		;;
 	  '-h'|'--help'|'--version'|'-v')
                 usage
@@ -76,7 +80,8 @@ while [ $# -gt 0 ]; do
                 break
 		;;
 	  *)
-		break
+	  	echo "Internal error!"
+		exit 1
 		;;
 	esac
 done
